/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile: any = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:34a93c9f-8f93-4ab3-91a9-660c8659edc2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_FiJ0rYvnS",
    "aws_user_pools_web_client_id": "4lfjgmj1m26ehl05hl1htt9afv",
    "oauth": {}
};

export default awsmobile;

