[package]
name = "simple_s3_cient"
version = "0.1.0"
authors = ["hyiromori <hyiromori@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusoto_core = "0.46.0"
rusoto_s3 = "0.46.0"
